/* Saveat — browser client. Authorization and inventory live in PostgreSQL. */
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v)===0?'Gratis':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v));
const when=v=>new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
let db=null,session=null,profile=null,current=null,myTab='reservations',page=0,itemSequence=0,routeGeneration=0;
let searchCity=null,publishCity=null,pendingRequest=null;
const config=window.SAVEAT_CONFIG||{};
function notice(text,error=false){$('message').textContent=text;$('message').hidden=false;$('message').className=error?'error':'';}
function errorText(error){const t=error?.message||'Operazione non riuscita. Riprova.';return /Failed to fetch|NetworkError|fetch failed/i.test(t)?'Connessione non disponibile. Controlla la rete e riprova.':t;}
async function run(button,work){if(button?.disabled)return;if(button)button.disabled=true;try{await work();}catch(e){notice(errorText(e),true);}finally{if(button)button.disabled=false;}}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
function requireAccount(){if(!session){location.hash='account';notice('Accedi per continuare.');return false;}if(!profile?.account_type){location.hash='account';notice('Completa il profilo per continuare.');return false;}return true;}
async function refreshProfile(){profile=null;if(session){const {data,error}=await db.from('saveat_profiles').select('*').eq('id',session.user.id).single();if(error)throw error;profile=data;}$('account-button').textContent=session?'Profilo':'Accedi';}
function accountView(){const signed=!!session;$('auth-form').hidden=signed;$('profile-form').hidden=!signed;
 if(signed){$('display-name').value=profile?.display_name||'';$('account-type').value=profile?.account_type||'private';$('account-type').disabled=!!profile?.account_type;$('business-name').value=profile?.business_name||'';businessView();}}
function businessView(){const biz=$('account-type').value==='business';$('business-field').hidden=!biz;$('business-name').required=biz;}
async function route(){const gen=++routeGeneration;const [raw,id]=(location.hash.slice(1)||'home').split('/');let screen=['home','cerca','pubblica','scheda','miei','account','setup'].includes(raw)?raw:'home';
 if(!db)screen='setup';else if(['pubblica','miei'].includes(screen)&&!requireAccount())return;
 document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==screen);document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+screen)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});window.scrollTo(0,0);
 try{if(screen==='account')accountView();if(screen==='home')await loadListings('home-list',true,gen);if(screen==='cerca'){page=0;await loadListings('search-list',false,gen);}if(screen==='pubblica'&&!$('item-fields').children.length)addItem();if(screen==='miei')await loadMine();if(screen==='scheda')await loadDetail(id);}catch(e){notice(errorText(e),true);}}
function listingCard(l){const photo=l.saveat_items?.find(i=>i.photo_path)?.photo_path;return `<article class="card">${photo?`<img class="photo" loading="lazy" src="${esc(db.storage.from('saveat-photos').getPublicUrl(photo).data.publicUrl)}" alt="Alimento disponibile">`:''}<div class="cardbody"><span class="pill">${l.account_type==='private'?'Privato':'Attività'}</span><h3>${esc(l.title)}</h3><p class="meta">${esc(l.saveat_municipalities?.name)} (${esc(l.saveat_municipalities?.province)}) · ${esc(l.seller_name)}</p><p>Ritiro entro ${esc(when(l.pickup_end))}</p><p>${(l.saveat_items||[]).filter(i=>Number(i.available)>0).map(i=>`${esc(i.name)} · ${esc(i.available)} ${esc(i.unit)} · ${money(i.price)}`).join('<br>')}</p><a class="btn primary" href="#scheda/${l.id}">Vedi e prenota</a></div></article>`;}
async function loadListings(target,home,gen=routeGeneration){$(target).innerHTML=page&& !home?$(target).innerHTML:'<p>Caricamento…</p>';
 const size=home?4:20;const data=await rpc('saveat_search',{p_query:home?'':$('search').value.trim(),p_city:home?null:searchCity?.code||null,p_page:home?0:page,p_size:size});if(gen!==routeGeneration)return;
 const visible=data.filter(l=>l.saveat_items.some(i=>Number(i.available)>0));const content=visible.map(listingCard).join('');
 if(page&&!home)$(target).insertAdjacentHTML('beforeend',content);else $(target).innerHTML=content||'<p class="empty">Nessun alimento disponibile. Puoi essere il primo a condividere qualcosa.</p>';
 if(!home)$('load-more').hidden=data.length<size;}
async function loadDetail(id){$('detail').innerHTML='<p>Caricamento…</p>';pendingRequest=null;
 const {data:l,error}=await db.from('saveat_listings').select('*,saveat_items(*),saveat_municipalities(name,province)').eq('id',id).single();if(error)throw error;current=l;
 const owner=session?.user.id===l.owner_id,active=l.status==='active'&&new Date(l.pickup_end)>new Date();
 $('detail').innerHTML=`<h1>${esc(l.title)}</h1><p class="lead">${esc(l.description)}</p><p>${esc(l.saveat_municipalities.name)} (${esc(l.saveat_municipalities.province)}) · ${esc(l.seller_name)}</p><p>Ritiro: ${esc(when(l.pickup_start))} – ${esc(when(l.pickup_end))}</p><form id="reserve-form">${l.saveat_items.map(i=>`<div class="product">${i.photo_path?`<img class="photo" src="${esc(db.storage.from('saveat-photos').getPublicUrl(i.photo_path).data.publicUrl)}" alt="${esc(i.name)}">`:''}<h2>${esc(i.name)}</h2><p>${esc(i.available)} ${esc(i.unit)} disponibili · ${money(i.price)} / ${esc(i.unit)}</p>${i.label_date?`<p>${i.date_type==='use_by'?'Da consumare entro':'Da consumarsi preferibilmente entro'}: ${esc(i.label_date)}</p>`:''}<p class="small">Allergeni / etichetta: ${esc(i.allergens||'Non indicati: verifica con chi pubblica.')}</p>${active&&!owner?`<label for="qty-${i.id}">Quantità da prenotare (${esc(i.unit)})</label><input class="qty" id="qty-${i.id}" data-item="${i.id}" type="number" min="0" max="${i.available}" step="${['kg','litri'].includes(i.unit)?'.001':'1'}" value="0">`:''}</div>`).join('')}${active&&!owner?'<div class="ethic">Prenota solo ciò che consumerai. Dopo la prenotazione vedrai i dettagli per il ritiro.</div><button class="primary full">Prenota gli alimenti selezionati</button>':`<p class="ethic">${owner?'Questo è il tuo annuncio. Gestiscilo in I miei Save.':'Annuncio non più disponibile.'}</p>`}</form>`;
 $('reserve-form').addEventListener('submit',e=>{e.preventDefault();run(e.submitter,async()=>{if(!requireAccount())return;const items=[...document.querySelectorAll('[data-item]')].map(i=>({item_id:i.dataset.item,quantity:Number(i.value)})).filter(i=>i.quantity>0);if(!items.length)throw new Error('Scegli almeno un alimento.');const signature=JSON.stringify(items);if(!pendingRequest||pendingRequest.signature!==signature)pendingRequest={signature,id:crypto.randomUUID()};await rpc('saveat_reserve',{p_listing_id:l.id,p_items:items,p_request_id:pendingRequest.id});pendingRequest=null;location.hash='miei';notice('Prenotazione registrata. Trovi i dettagli del ritiro in I miei Save.');});});}
function addItem(){if($('item-fields').children.length>=20){notice('Massimo 20 alimenti per annuncio.',true);return;}const n=++itemSequence;const fs=document.createElement('fieldset');fs.className='item-field';fs.dataset.sequence=n;const field=(name,label,type='text',extra='')=>`<label for="item-${n}-${name}">${label}</label><input id="item-${n}-${name}" data-field="${name}" type="${type}" ${extra}>`;
 fs.innerHTML=`<legend>Alimento ${n}</legend>${field('name','Nome dell’alimento','text','required minlength="2" maxlength="120"')}<div class="two"><div>${field('quantity','Quantità disponibile','number','required min="0.001" max="9999999" step="0.001"')}</div><div><label for="item-${n}-unit">Unità</label><select id="item-${n}-unit" data-field="unit"><option>confezioni</option><option>pezzi</option><option>kg</option><option>litri</option></select></div></div>${field('price','Prezzo per unità (€), 0 per regalo','number',`required min="0" max="99999999" step="0.01" value="0" ${profile?.account_type==='private'?'readonly':''}`)}<label for="item-${n}-date-type">Tipo di data in etichetta</label><select id="item-${n}-date-type" data-field="date_type"><option value="none">Nessuna data</option><option value="use_by">Da consumare entro (scadenza)</option><option value="best_before">Da consumarsi preferibilmente entro</option></select>${field('label_date','Data sulla confezione','date')}${field('allergens','Allergeni e informazioni in etichetta','text','maxlength="500"')}${field('photo','Foto dell’alimento (max 5 MB)','file','accept="image/jpeg,image/png,image/webp"')}<p class="small">Non includere indirizzi, contatti o persone nelle foto pubbliche.</p><button type="button" class="ghost remove-item">Rimuovi alimento</button>`;
 fs.querySelector('.remove-item').onclick=()=>{if($('item-fields').children.length>1)fs.remove();else notice('L’annuncio deve contenere almeno un alimento.',true);};fs.querySelector('[data-field="date_type"]').onchange=e=>fs.querySelector('[data-field="label_date"]').required=e.target.value!=='none';$('item-fields').append(fs);}
async function publish(){if(!requireAccount())return;if(!publishCity)throw new Error('Seleziona un comune dai suggerimenti.');const start=new Date($('pickup-start').value),end=new Date($('pickup-end').value);if(end<=new Date()||end<=start)throw new Error('Controlla la fascia di ritiro.');
 const items=[];for(const fs of $('item-fields').children){const get=f=>fs.querySelector(`[data-field="${f}"]`);const item={name:get('name').value,quantity:Number(get('quantity').value),unit:get('unit').value,price:Number(get('price').value),date_type:get('date_type').value,label_date:get('label_date').value||null,allergens:get('allergens').value,photo_path:null};
  if(['pezzi','confezioni'].includes(item.unit)&&!Number.isInteger(item.quantity))throw new Error('Pezzi e confezioni richiedono quantità intere.');
  const file=get('photo').files[0];if(file){if(file.size>5242880||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Foto: usa JPG, PNG o WebP entro 5 MB.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const path=session.user.id+'/'+crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('saveat-photos').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;item.photo_path=path;}items.push(item);}
 await rpc('saveat_create_listing',{p_listing:{title:$('title').value,description:$('description').value,municipality_code:publishCity.code,pickup_start:start.toISOString(),pickup_end:end.toISOString(),address:$('address').value,contact:$('contact').value,instructions:$('instructions').value},p_items:items});$('publish-form').reset();$('item-fields').replaceChildren();publishCity=null;location.hash='miei';myTab='listings';notice('Annuncio pubblicato.');}
const statusNames={reserved:'Prenotato',confirmed:'Confermato',collected:'Ritirato',cancelled:'Annullato',expired:'Scaduto'};
async function loadMine(){if(!requireAccount())return;$('reservations-tab').className=myTab==='reservations'?'primary':'ghost';$('listings-tab').className=myTab==='listings'?'primary':'ghost';$('reservations-tab').setAttribute('aria-pressed',myTab==='reservations');$('listings-tab').setAttribute('aria-pressed',myTab==='listings');$('my-content').innerHTML='<p>Caricamento…</p>';
 if(myTab==='listings'){const {data,error}=await db.from('saveat_listings').select('*,saveat_items(*),saveat_municipalities(name,province)').eq('owner_id',session.user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;$('my-content').innerHTML=data.map(l=>`<article class="card padded"><h2>${esc(l.title)}</h2><p>${l.status==='closed'?'Chiuso':new Date(l.pickup_end)<=new Date()?'Scaduto':'Attivo'} · ritiro entro ${esc(when(l.pickup_end))}</p><p>${l.saveat_items.map(i=>`${esc(i.name)}: ${esc(i.available)} / ${esc(i.quantity)} ${esc(i.unit)}`).join('<br>')}</p><a class="btn ghost" href="#scheda/${l.id}">Vedi annuncio</a>${l.status==='active'?`<button class="ghost" data-close="${l.id}">Chiudi annuncio</button>`:''}</article>`).join('')||'<p class="empty">Non hai ancora pubblicato annunci.</p>';
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!confirm('Chiudere questo annuncio? Le prenotazioni attive saranno annullate.'))return;run(b,async()=>{await rpc('saveat_close_listing',{p_id:b.dataset.close});await loadMine();notice('Annuncio chiuso.');});});return;}
 const data=await rpc('saveat_my_reservations');$('my-content').innerHTML=data.map(r=>{const owner=r.owner_id===session.user.id,active=['reserved','confirmed'].includes(r.status);return `<article class="card padded"><span class="pill">${esc(statusNames[r.status])} · ${owner?'Ricevuta':'La tua prenotazione'}</span><h2>${esc(r.title)}</h2><p class="small">Codice: ${esc(r.id.slice(0,8))}</p><p>${r.items.map(i=>`${esc(i.name)} · ${esc(i.quantity)} ${esc(i.unit)} · ${money(Number(i.price)*Number(i.quantity))}`).join('<br>')}</p><p>Totale: ${money(r.items.reduce((s,i)=>s+Number(i.quantity)*Number(i.price),0))}</p><p>Ritiro: ${esc(when(r.pickup_start))} – ${esc(when(r.pickup_end))}</p>${r.pickup?`<div class="ethic"><b>Punto di ritiro</b><p>${esc(r.pickup.address)}</p><p>Contatto: ${esc(r.pickup.contact)}</p><p>${esc(r.pickup.instructions)}</p></div>`:''}<div class="row">${active&&owner&&r.status==='reserved'?`<button class="primary" data-transition="confirmed" data-id="${r.id}">Conferma prenotazione</button>`:''}${active&&owner&&new Date(r.pickup_start)<=new Date()?`<button class="primary" data-transition="collected" data-id="${r.id}">Conferma ritiro</button>`:''}${active?`<button class="ghost" data-transition="cancelled" data-id="${r.id}">Annulla prenotazione</button>`:''}</div></article>`;}).join('')||'<p class="empty">Qui troverai le tue prenotazioni e quelle ricevute.</p>';
 document.querySelectorAll('[data-transition]').forEach(b=>b.onclick=()=>{if(b.dataset.transition==='cancelled'&&!confirm('Annullare la prenotazione?'))return;run(b,async()=>{const state=await rpc('saveat_transition',{p_id:b.dataset.id,p_status:b.dataset.transition});await loadMine();notice('Stato aggiornato: '+statusNames[state]+'.');});});}
function cityPicker(prefix,onPick){const input=$(prefix+'-city'),box=$(prefix+'-city-options');let timer,sequence=0;input.addEventListener('input',()=>{onPick(null);clearTimeout(timer);const n=++sequence;const text=input.value.trim();box.hidden=true;input.setAttribute('aria-expanded','false');if(text.length<2||!db)return;timer=setTimeout(async()=>{try{const {data,error}=await db.from('saveat_municipalities').select('code,name,province').ilike('name',text.replace(/[%,_]/g,'')+'%').order('name').limit(12);if(error)throw error;if(n!==sequence)return;box.replaceChildren();data.forEach(c=>{const b=document.createElement('button');b.type='button';b.role='option';b.textContent=c.name+' ('+c.province+')';b.onclick=()=>{onPick(c);input.value=b.textContent;box.hidden=true;input.setAttribute('aria-expanded','false');input.focus();};box.append(b);});box.hidden=!data.length;input.setAttribute('aria-expanded',String(!!data.length));}catch(e){notice(errorText(e),true);}},180);});input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&!box.hidden){e.preventDefault();box.querySelector('button')?.focus();}if(e.key==='Escape'){box.hidden=true;input.setAttribute('aria-expanded','false');}});box.addEventListener('keydown',e=>{const buttons=[...box.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(e.key==='Escape'){box.hidden=true;input.setAttribute('aria-expanded','false');input.focus();}});document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target)){box.hidden=true;input.setAttribute('aria-expanded','false');}});}
function safeConfig(url,key){const u=new URL(url);if(u.protocol!=='https:'||!u.hostname.endsWith('.supabase.co')||u.username||u.password||u.pathname!=='/')throw new Error('Usa il Project URL https://…supabase.co del progetto.');if(key.startsWith('sb_secret_'))throw new Error('Questa è una chiave segreta. Usa la publishable key.');if(!key.startsWith('sb_publishable_')){try{const payload=JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(payload.role!=='anon')throw Error();}catch{throw new Error('Usa una publishable key o la chiave anon pubblica.');}}return {url:u.origin,key};}
$('setup-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const c=safeConfig($('supabase-url').value.trim(),$('supabase-key').value.trim());const blob=new Blob(['window.SAVEAT_CONFIG = '+JSON.stringify(c)+';\n'],{type:'text/javascript'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='config.js';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);notice('Configurazione scaricata. Sostituisci config.js nel sito e ricarica.');});};
$('account-button').onclick=()=>location.hash='account';$('account-type').onchange=businessView;$('add-item').onclick=addItem;
$('publish-form').onsubmit=e=>{e.preventDefault();run(e.submitter,publish);};
$('search-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{page=0;await loadListings('search-list',false);});};
$('clear-search').onclick=()=>{searchCity=null;$('search-city').value='';$('search').value='';page=0;run($('clear-search'),()=>loadListings('search-list',false));};
$('load-more').onclick=()=>run($('load-more'),async()=>{page++;try{await loadListings('search-list',false);}catch(e){page--;throw e;}});
$('reservations-tab').onclick=()=>{myTab='reservations';run($('reservations-tab'),loadMine);};$('listings-tab').onclick=()=>{myTab='listings';run($('listings-tab'),loadMine);};
$('auth-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const credentials={email:$('email').value.trim(),password:$('password').value};const intent=e.submitter.value;const {data,error}=intent==='signup'?await db.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+location.pathname+'#account'}}):await db.auth.signInWithPassword(credentials);if(error)throw error;session=data.session;$('password').value='';await refreshProfile();accountView();notice(session?'Accesso riuscito.':'Controlla la tua email e conferma l’iscrizione prima di accedere.');});};
$('forgot').onclick=()=>run($('forgot'),async()=>{if(!$('email').checkValidity()||!$('email').value)throw new Error('Inserisci la tua email.');const {error}=await db.auth.resetPasswordForEmail($('email').value.trim(),{redirectTo:location.origin+location.pathname+'#account'});if(error)throw error;notice('Se esiste un account, riceverai un link per reimpostare la password.');});
$('reset-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const {error}=await db.auth.updateUser({password:$('new-password').value});if(error)throw error;$('reset-form').reset();$('reset-form').hidden=true;notice('Password aggiornata.');});};
$('profile-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{await rpc('saveat_set_profile',{p_name:$('display-name').value,p_type:$('account-type').value,p_business:$('business-name').value});await refreshProfile();accountView();notice('Profilo salvato. Ora puoi pubblicare e prenotare.');});};
$('logout').onclick=()=>run($('logout'),async()=>{const {error}=await db.auth.signOut();if(error)throw error;session=null;profile=null;location.hash='home';await route();notice('Sei uscito dal tuo account.');});
cityPicker('search',c=>searchCity=c);cityPicker('publish',c=>publishCity=c);window.addEventListener('hashchange',route);
(async()=>{try{if(config.url&&config.key){const c=safeConfig(config.url,config.key);if(!window.supabase)throw new Error('Libreria Supabase non disponibile.');db=window.supabase.createClient(c.url,c.key);db.auth.onAuthStateChange((event,s)=>{session=s;if(event==='PASSWORD_RECOVERY'){$('reset-form').hidden=false;location.hash='account';}if(['SIGNED_OUT','TOKEN_REFRESHED'].includes(event))setTimeout(()=>run(null,async()=>{await refreshProfile();if(location.hash.startsWith('#account'))accountView();}),0);});const {data,error}=await db.auth.getSession();if(error)throw error;session=data.session;await refreshProfile();}await route();}catch(e){notice(errorText(e),true);}})();
